// Pod Creation Flow - Components and Flow Data

import type { PodCreationComponent, PodCreationStep } from './types';

export const podCreationComponents: PodCreationComponent[] = [
  // Client Zone
  {
    id: 'user',
    name: 'User',
    description: 'Developer or operator initiating the pod creation',
    shape: 'circle',
    color: '#94a3b8',
    position: { x: 40, y: 200 },
    zone: 'client',
  },
  {
    id: 'kubectl',
    name: 'kubectl',
    description: 'Kubernetes CLI tool that sends requests to API Server',
    shape: 'rectangle',
    color: '#64748b',
    position: { x: 130, y: 200 },
    zone: 'client',
  },

  // API Layer
  {
    id: 'api-server',
    name: 'API Server',
    description: 'Central hub that processes all API requests',
    shape: 'hexagon',
    color: '#326CE5',
    position: { x: 320, y: 200 },
    zone: 'api-layer',
  },
  {
    id: 'auth-module',
    name: 'Auth Module',
    description: 'Handles authentication (certificates, tokens) and authorization (RBAC)',
    shape: 'diamond',
    color: '#f59e0b',
    position: { x: 280, y: 80 },
    zone: 'api-layer',
  },
  {
    id: 'admission-controller',
    name: 'Admission Controller',
    description: 'Validates and mutates requests (webhooks, policies)',
    shape: 'pentagon',
    color: '#8b5cf6',
    position: { x: 400, y: 80 },
    zone: 'api-layer',
  },

  // Control Plane
  {
    id: 'etcd',
    name: 'etcd',
    description: 'Distributed key-value store - source of truth for cluster state',
    shape: 'circle',
    color: '#419eda',
    position: { x: 520, y: 200 },
    zone: 'control-plane',
  },
  {
    id: 'scheduler',
    name: 'Scheduler',
    description: 'Watches for unscheduled pods and assigns them to nodes',
    shape: 'triangle',
    color: '#22c55e',
    position: { x: 440, y: 320 },
    zone: 'control-plane',
  },
  {
    id: 'node-filter',
    name: 'Node Filter',
    description: 'Filters nodes based on taints, tolerations, resources, affinity',
    shape: 'diamond',
    color: '#14b8a6',
    position: { x: 340, y: 400 },
    zone: 'control-plane',
  },
  {
    id: 'node-scorer',
    name: 'Node Scorer',
    description: 'Scores feasible nodes based on priorities and preferences',
    shape: 'diamond',
    color: '#06b6d4',
    position: { x: 540, y: 400 },
    zone: 'control-plane',
  },

  // Worker Node
  {
    id: 'kubelet',
    name: 'Kubelet',
    description: 'Node agent that manages pod lifecycle on the node',
    shape: 'octagon',
    color: '#ec4899',
    position: { x: 700, y: 120 },
    zone: 'worker-node',
  },
  {
    id: 'cri',
    name: 'CRI',
    description: 'Container Runtime Interface - abstraction layer for container runtimes',
    shape: 'square',
    color: '#f97316',
    position: { x: 700, y: 240 },
    zone: 'worker-node',
  },
  {
    id: 'container-runtime',
    name: 'containerd',
    description: 'Container runtime that manages container lifecycle',
    shape: 'square',
    color: '#06b6d4',
    position: { x: 700, y: 360 },
    zone: 'worker-node',
  },
  {
    id: 'pod-sandbox',
    name: 'Pod Sandbox',
    description: 'Network namespace and shared resources for pod containers',
    shape: 'rectangle',
    color: '#a855f7',
    position: { x: 850, y: 240 },
    zone: 'worker-node',
  },
  {
    id: 'container',
    name: 'Container',
    description: 'Running container instance with application',
    shape: 'square',
    color: '#3b82f6',
    position: { x: 920, y: 360 },
    zone: 'worker-node',
  },
  {
    id: 'pod',
    name: 'Pod',
    description: 'Running pod with all containers started',
    shape: 'circle',
    color: '#10b981',
    position: { x: 920, y: 240 },
    zone: 'worker-node',
  },

  // External
  {
    id: 'image-registry',
    name: 'Image Registry',
    description: 'Container image repository (Docker Hub, GCR, ECR)',
    shape: 'hexagon',
    color: '#0ea5e9',
    position: { x: 850, y: 450 },
    zone: 'external',
  },
];

export const podCreationSteps: PodCreationStep[] = [
  {
    id: 'step1',
    from: 'user',
    to: 'kubectl',
    label: '1. User Command',
    description: 'User runs kubectl create pod or kubectl apply -f pod.yaml',
    duration: 1200,
    details: [
      'kubectl reads kubeconfig for cluster connection',
      'Parses YAML/JSON manifest or CLI flags',
      'Prepares HTTP request to API Server',
    ],
  },
  {
    id: 'step2',
    from: 'kubectl',
    to: 'api-server',
    label: '2. API Request',
    description: 'kubectl sends POST request to /api/v1/namespaces/{ns}/pods',
    duration: 1000,
    details: [
      'HTTPS request with bearer token or client certificate',
      'Request body contains pod specification',
      'API Server receives and begins processing',
    ],
  },
  {
    id: 'step3',
    from: 'api-server',
    to: 'auth-module',
    label: '3. Authentication',
    description: 'API Server validates identity via certificates, tokens, or OIDC',
    duration: 1200,
    details: [
      'Validates client certificate or bearer token',
      'Checks token expiration and signature',
      'Extracts user identity and groups',
    ],
  },
  {
    id: 'step4',
    from: 'auth-module',
    to: 'api-server',
    label: '4. Authorization (RBAC)',
    description: 'Checks if user has permission to create pods in namespace',
    duration: 1000,
    details: [
      'Evaluates RBAC rules (Role, ClusterRole)',
      'Checks RoleBindings and ClusterRoleBindings',
      'Verifies verb "create" on resource "pods"',
    ],
  },
  {
    id: 'step5',
    from: 'api-server',
    to: 'admission-controller',
    label: '5. Admission Control',
    description: 'Mutating and validating webhooks process the request',
    duration: 1500,
    details: [
      'Mutating webhooks can modify pod spec',
      'Adds default values, injects sidecars',
      'Validating webhooks enforce policies',
      'PodSecurityPolicy/Standards checks',
    ],
  },
  {
    id: 'step6',
    from: 'admission-controller',
    to: 'api-server',
    label: '6. Validation Complete',
    description: 'Pod spec passes all admission checks',
    duration: 800,
    details: [
      'All webhooks returned success',
      'Pod spec is valid and compliant',
      'Ready to persist to etcd',
    ],
  },
  {
    id: 'step7',
    from: 'api-server',
    to: 'etcd',
    label: '7. Persist to etcd',
    description: 'Pod object stored in etcd with status "Pending"',
    duration: 1200,
    details: [
      'Pod object serialized to protobuf',
      'Written to etcd with key /registry/pods/{ns}/{name}',
      'Status set to Pending, no nodeName yet',
    ],
  },
  {
    id: 'step8',
    from: 'etcd',
    to: 'scheduler',
    label: '8. Scheduler Watch',
    description: 'Scheduler detects new pod without nodeName via watch API',
    duration: 1000,
    details: [
      'Scheduler watches pods with spec.nodeName=""',
      'Receives watch event for new pod',
      'Adds pod to scheduling queue',
    ],
  },
  {
    id: 'step9',
    from: 'scheduler',
    to: 'node-filter',
    label: '9. Node Filtering',
    description: 'Filter nodes that can run the pod',
    duration: 1500,
    details: [
      'Check node taints vs pod tolerations',
      'Verify resource availability (CPU, memory)',
      'Apply nodeSelector and nodeAffinity',
      'Check PodAntiAffinity rules',
    ],
  },
  {
    id: 'step10',
    from: 'node-filter',
    to: 'node-scorer',
    label: '10. Node Scoring',
    description: 'Score feasible nodes to find the best fit',
    duration: 1200,
    details: [
      'LeastRequestedPriority - prefer less loaded nodes',
      'BalancedResourceAllocation - balance CPU/memory',
      'NodeAffinityPriority - prefer matching nodes',
      'Calculate final weighted score',
    ],
  },
  {
    id: 'step11',
    from: 'node-scorer',
    to: 'scheduler',
    label: '11. Node Selected',
    description: 'Highest scoring node is selected for pod placement',
    duration: 800,
    details: [
      'Node with highest score wins',
      'Scheduler creates binding decision',
      'Prepares to update pod spec',
    ],
  },
  {
    id: 'step12',
    from: 'scheduler',
    to: 'api-server',
    label: '12. Bind Pod to Node',
    description: 'Scheduler updates pod with selected nodeName',
    duration: 1000,
    details: [
      'POST /api/v1/namespaces/{ns}/pods/{name}/binding',
      'Sets spec.nodeName to selected node',
      'Binding is persisted to etcd',
    ],
  },
  {
    id: 'step13',
    from: 'api-server',
    to: 'kubelet',
    label: '13. Kubelet Watch',
    description: 'Kubelet on target node detects pod assignment',
    duration: 1200,
    details: [
      'Kubelet watches pods with spec.nodeName=thisNode',
      'Receives watch event for newly bound pod',
      'Begins pod creation process',
    ],
  },
  {
    id: 'step14',
    from: 'kubelet',
    to: 'cri',
    label: '14. CRI: Create Sandbox',
    description: 'Kubelet calls CRI to create pod sandbox (network namespace)',
    duration: 1500,
    details: [
      'RunPodSandbox RPC call',
      'Creates network namespace',
      'Sets up pod networking (CNI)',
      'Allocates pod IP address',
    ],
  },
  {
    id: 'step15',
    from: 'cri',
    to: 'pod-sandbox',
    label: '15. Sandbox Created',
    description: 'Pod sandbox with network namespace is ready',
    duration: 1000,
    details: [
      'Network namespace created',
      'CNI plugin configured networking',
      'Pod has IP address assigned',
      'Ready for containers',
    ],
  },
  {
    id: 'step16',
    from: 'cri',
    to: 'container-runtime',
    label: '16. Pull Image',
    description: 'Container runtime pulls container image',
    duration: 2000,
    details: [
      'Check if image exists locally',
      'Pull from registry if needed',
      'Verify image signature (if enabled)',
      'Extract image layers',
    ],
  },
  {
    id: 'step17',
    from: 'container-runtime',
    to: 'image-registry',
    label: '17. Image Download',
    description: 'Download image layers from container registry',
    duration: 2500,
    details: [
      'Authenticate with registry',
      'Download manifest and layers',
      'Decompress and store layers',
      'Image ready for use',
    ],
  },
  {
    id: 'step18',
    from: 'image-registry',
    to: 'container-runtime',
    label: '18. Image Ready',
    description: 'Image successfully pulled and cached locally',
    duration: 800,
    details: [
      'All layers downloaded',
      'Image stored in local cache',
      'Ready to create container',
    ],
  },
  {
    id: 'step19',
    from: 'container-runtime',
    to: 'container',
    label: '19. Create Container',
    description: 'Create and start the container process',
    duration: 1500,
    details: [
      'CreateContainer RPC call',
      'Set up container filesystem',
      'Configure cgroups and namespaces',
      'StartContainer RPC call',
    ],
  },
  {
    id: 'step20',
    from: 'container',
    to: 'pod',
    label: '20. Container Running',
    description: 'Container process started, pod enters Running state',
    duration: 1200,
    details: [
      'Container process is running',
      'Liveness/readiness probes start',
      'Pod status updated to Running',
      'Pod is ready to serve traffic',
    ],
  },
];

export function getComponentById(id: string): PodCreationComponent | undefined {
  return podCreationComponents.find(c => c.id === id);
}
