// Service Discovery Flow - Components and Flow Data

import type { ServiceDiscoveryComponent, ServiceDiscoveryStep } from './types';

export const serviceDiscoveryComponents: ServiceDiscoveryComponent[] = [
  // Application Zone - Client Pod
  {
    id: 'client-pod',
    name: 'Client Pod',
    description: 'Application pod that needs to connect to a backend service. Initiates DNS lookup and HTTP request.',
    shape: 'hexagon',
    color: '#3b82f6',
    position: { x: 50, y: 195 },
    zone: 'application',
    ipAddress: '10.244.1.5',
  },

  // DNS Layer
  {
    id: 'coredns',
    name: 'CoreDNS',
    description: 'Kubernetes DNS server that resolves service names to ClusterIP addresses. Runs as a deployment in kube-system namespace.',
    shape: 'hexagon',
    color: '#8b5cf6',
    position: { x: 220, y: 55 },
    zone: 'dns-layer',
    ipAddress: '10.96.0.10',
    port: 53,
  },

  // Control Plane
  {
    id: 'api-server',
    name: 'API Server',
    description: 'Central hub that CoreDNS watches for Service and Endpoints changes.',
    shape: 'hexagon',
    color: '#326CE5',
    position: { x: 420, y: 55 },
    zone: 'control-plane',
  },
  {
    id: 'etcd',
    name: 'etcd',
    description: 'Stores all cluster state including Services and Endpoints objects.',
    shape: 'circle',
    color: '#419eda',
    position: { x: 550, y: 55 },
    zone: 'control-plane',
  },
  {
    id: 'endpoints',
    name: 'Endpoints',
    description: 'Object that maps a Service to the IP addresses of its backing pods. Auto-updated by Endpoints controller.',
    shape: 'rectangle',
    color: '#f59e0b',
    position: { x: 480, y: 145 },
    zone: 'control-plane',
  },

  // Networking Layer
  {
    id: 'kube-proxy',
    name: 'kube-proxy',
    description: 'Network proxy running on each node. Maintains iptables/IPVS rules for Service routing.',
    shape: 'octagon',
    color: '#f97316',
    position: { x: 220, y: 310 },
    zone: 'networking',
  },
  {
    id: 'iptables',
    name: 'iptables/IPVS',
    description: 'Linux kernel networking rules that perform DNAT (Destination NAT) to route traffic from ClusterIP to Pod IPs.',
    shape: 'diamond',
    color: '#ef4444',
    position: { x: 370, y: 310 },
    zone: 'networking',
  },
  {
    id: 'service',
    name: 'Service',
    description: 'Kubernetes Service object providing stable ClusterIP. Acts as virtual load balancer for pods.',
    shape: 'hexagon',
    color: '#6366f1',
    position: { x: 220, y: 195 },
    zone: 'networking',
    ipAddress: '10.96.100.50',
    port: 80,
  },

  // Workloads - Backend Pods
  {
    id: 'pod-1',
    name: 'Pod 1',
    description: 'First replica of the backend service. Receives load-balanced traffic.',
    shape: 'circle',
    color: '#10b981',
    position: { x: 560, y: 310 },
    zone: 'workloads',
    ipAddress: '10.244.2.10',
    port: 8080,
  },
  {
    id: 'pod-2',
    name: 'Pod 2',
    description: 'Second replica of the backend service. Receives load-balanced traffic.',
    shape: 'circle',
    color: '#10b981',
    position: { x: 650, y: 310 },
    zone: 'workloads',
    ipAddress: '10.244.3.15',
    port: 8080,
  },
  {
    id: 'pod-3',
    name: 'Pod 3',
    description: 'Third replica of the backend service. Receives load-balanced traffic.',
    shape: 'circle',
    color: '#10b981',
    position: { x: 740, y: 310 },
    zone: 'workloads',
    ipAddress: '10.244.1.20',
    port: 8080,
  },
];

export const serviceDiscoverySteps: ServiceDiscoveryStep[] = [
  {
    id: 'step1',
    from: 'client-pod',
    to: 'coredns',
    label: '1. DNS Query',
    description: 'Client pod needs to connect to "my-service". It sends a DNS query to CoreDNS (configured in /etc/resolv.conf).',
    duration: 1500,
    packetType: 'dns-query',
    packetLabel: 'DNS?',
    details: [
      'Query: my-service.default.svc.cluster.local',
      'DNS server: 10.96.0.10:53 (CoreDNS)',
      'Query type: A record (IPv4 address)',
      'Source: /etc/resolv.conf in pod',
    ],
  },
  {
    id: 'step2',
    from: 'coredns',
    to: 'api-server',
    label: '2. Service Lookup',
    description: 'CoreDNS checks its cache. On cache miss, it queries the API Server for the Service object.',
    duration: 1200,
    packetType: 'data',
    details: [
      'CoreDNS watches Services via API Server',
      'Uses kubernetes plugin for in-cluster resolution',
      'Caches responses for performance',
      'TTL typically 30 seconds',
    ],
  },
  {
    id: 'step3',
    from: 'api-server',
    to: 'etcd',
    label: '3. Fetch from etcd',
    description: 'API Server retrieves the Service object from etcd, which contains the ClusterIP.',
    duration: 1000,
    packetType: 'data',
    details: [
      'Service stored at /registry/services/default/my-service',
      'Contains spec.clusterIP: 10.96.100.50',
      'Contains spec.ports and selector',
    ],
  },
  {
    id: 'step4',
    from: 'api-server',
    to: 'coredns',
    label: '4. Return Service Info',
    description: 'API Server returns the Service object with ClusterIP to CoreDNS.',
    duration: 1000,
    packetType: 'data',
    details: [
      'Service ClusterIP: 10.96.100.50',
      'Service Port: 80',
      'CoreDNS caches this response',
    ],
  },
  {
    id: 'step5',
    from: 'coredns',
    to: 'client-pod',
    label: '5. DNS Response',
    description: 'CoreDNS returns the ClusterIP address to the client pod.',
    duration: 1200,
    packetType: 'dns-response',
    packetLabel: '10.96.100.50',
    details: [
      'Response: my-service.default.svc.cluster.local → 10.96.100.50',
      'Record type: A (IPv4)',
      'TTL: 30 seconds',
      'Client now knows the Service IP',
    ],
  },
  {
    id: 'step6',
    from: 'client-pod',
    to: 'service',
    label: '6. Connect to ClusterIP',
    description: 'Client pod initiates TCP connection to the Service ClusterIP (10.96.100.50:80).',
    duration: 1500,
    packetType: 'http-request',
    packetLabel: 'HTTP',
    details: [
      'Destination: 10.96.100.50:80',
      'This is a virtual IP (VIP)',
      'No actual endpoint listens on this IP',
      'Packet will be intercepted by iptables',
    ],
  },
  {
    id: 'step7',
    from: 'service',
    to: 'kube-proxy',
    label: '7. kube-proxy Rules',
    description: 'kube-proxy has programmed iptables/IPVS rules that intercept traffic to ClusterIP.',
    duration: 1200,
    packetType: 'data',
    details: [
      'kube-proxy watches Services and Endpoints',
      'Programs iptables DNAT rules',
      'Or IPVS virtual servers (if enabled)',
      'Rules updated on Service/Endpoint changes',
    ],
  },
  {
    id: 'step8',
    from: 'kube-proxy',
    to: 'endpoints',
    label: '8. Get Endpoints',
    description: 'kube-proxy knows the Endpoints (pod IPs) for this Service from watching the API.',
    duration: 1000,
    packetType: 'data',
    details: [
      'Endpoints object: my-service',
      'Subsets contain ready pod IPs:',
      '  - 10.244.2.10:8080',
      '  - 10.244.3.15:8080',
      '  - 10.244.1.20:8080',
    ],
  },
  {
    id: 'step9',
    from: 'kube-proxy',
    to: 'iptables',
    label: '9. DNAT Rules',
    description: 'iptables performs DNAT (Destination NAT) to rewrite the destination IP from ClusterIP to a Pod IP.',
    duration: 1500,
    packetType: 'data',
    details: [
      'Chain: KUBE-SERVICES → KUBE-SVC-XXX',
      'Random selection with probability',
      'DNAT: 10.96.100.50 → 10.244.2.10',
      'Connection tracking maintains session',
    ],
  },
  {
    id: 'step10',
    from: 'iptables',
    to: 'pod-1',
    label: '10. Route to Pod',
    description: 'Packet is routed to the selected backend pod. Load balancing distributes across replicas.',
    duration: 1200,
    packetType: 'http-request',
    packetLabel: 'HTTP',
    details: [
      'Destination rewritten to: 10.244.2.10:8080',
      'Packet routed via CNI network',
      'Pod receives request on port 8080',
      'Source IP preserved (or SNAT depending on config)',
    ],
  },
  {
    id: 'step11',
    from: 'pod-1',
    to: 'iptables',
    label: '11. Response',
    description: 'Backend pod processes the request and sends response back.',
    duration: 1200,
    packetType: 'http-response',
    packetLabel: '200 OK',
    details: [
      'Pod sends response to client IP',
      'Connection tracking ensures correct routing',
      'Response follows reverse path',
    ],
  },
  {
    id: 'step12',
    from: 'iptables',
    to: 'client-pod',
    label: '12. Response Delivered',
    description: 'Response is delivered to the client pod. The client sees it as coming from the Service IP.',
    duration: 1000,
    packetType: 'http-response',
    packetLabel: '200 OK',
    details: [
      'SNAT reverses the translation',
      'Client sees response from 10.96.100.50',
      'Transparent to the application',
      'Service discovery complete!',
    ],
  },
];

export function getComponentById(id: string): ServiceDiscoveryComponent | undefined {
  return serviceDiscoveryComponents.find(c => c.id === id);
}

export const dnsExplanation = {
  fqdn: 'my-service.default.svc.cluster.local',
  parts: [
    { part: 'my-service', description: 'Service name' },
    { part: 'default', description: 'Namespace' },
    { part: 'svc', description: 'Service subdomain' },
    { part: 'cluster.local', description: 'Cluster domain' },
  ],
  shortNames: [
    'my-service (same namespace)',
    'my-service.default (cross-namespace)',
    'my-service.default.svc (explicit)',
  ],
};

export const iptablesRules = [
  {
    chain: 'KUBE-SERVICES',
    rule: '-d 10.96.100.50/32 -p tcp --dport 80 -j KUBE-SVC-XXXX',
    description: 'Match traffic to Service ClusterIP',
  },
  {
    chain: 'KUBE-SVC-XXXX',
    rule: '-m statistic --mode random --probability 0.333 -j KUBE-SEP-AAA',
    description: 'Load balance to endpoint 1 (33% chance)',
  },
  {
    chain: 'KUBE-SEP-AAA',
    rule: '-p tcp -j DNAT --to-destination 10.244.2.10:8080',
    description: 'DNAT to Pod 1 IP',
  },
];
