// Pod-to-Pod Communication Flow - Components and Flow Data

import type { PodToPodComponent, PodToPodStep } from './types';

export const podToPodComponents: PodToPodComponent[] = [
  // Node 1 - Source Pod
  {
    id: 'pod-a',
    name: 'Pod A',
    description: 'Source pod initiating communication. Runs the application that needs to connect to Pod B.',
    shape: 'hexagon',
    color: '#3b82f6',
    position: { x: 35, y: 80 },
    zone: 'pod-a-zone',
    ipAddress: '10.244.1.5',
  },
  {
    id: 'pod-a-netns',
    name: 'Net NS',
    description: 'Network namespace for Pod A. Isolated network stack with its own interfaces, routes, and iptables.',
    shape: 'rectangle',
    color: '#6366f1',
    position: { x: 30, y: 165 },
    zone: 'pod-a-zone',
  },
  {
    id: 'veth-a',
    name: 'veth pair',
    description: 'Virtual ethernet pair connecting pod namespace to the bridge. One end in pod (eth0), other on host.',
    shape: 'pipe',
    color: '#8b5cf6',
    position: { x: 170, y: 100 },
    zone: 'node-1',
  },
  {
    id: 'bridge-1',
    name: 'CNI Bridge',
    description: 'Linux bridge (cbr0/cni0) connecting all pods on this node. Acts as a virtual switch.',
    shape: 'rectangle',
    color: '#22c55e',
    position: { x: 250, y: 120 },
    zone: 'node-1',
    ipAddress: '10.244.1.1',
  },
  {
    id: 'node-1-eth',
    name: 'eth0',
    description: 'Physical network interface of Node 1. Connected to the cluster network.',
    shape: 'square',
    color: '#f59e0b',
    position: { x: 350, y: 120 },
    zone: 'node-1',
    ipAddress: '192.168.1.10',
  },

  // Overlay Network
  {
    id: 'overlay-network',
    name: 'Overlay',
    description: 'VXLAN/IPinIP tunnel encapsulating pod traffic. Allows pods on different nodes to communicate.',
    shape: 'cylinder',
    color: '#ec4899',
    position: { x: 425, y: 80 },
    zone: 'overlay',
  },
  {
    id: 'cni-plugin',
    name: 'CNI',
    description: 'Container Network Interface plugin (Calico/Flannel/Weave) managing pod networking and routes.',
    shape: 'diamond',
    color: '#14b8a6',
    position: { x: 440, y: 185 },
    zone: 'overlay',
  },

  // Node 2 - Destination Pod
  {
    id: 'node-2-eth',
    name: 'eth0',
    description: 'Physical network interface of Node 2. Receives encapsulated traffic from overlay.',
    shape: 'square',
    color: '#f59e0b',
    position: { x: 530, y: 120 },
    zone: 'node-2',
    ipAddress: '192.168.1.11',
  },
  {
    id: 'bridge-2',
    name: 'CNI Bridge',
    description: 'Linux bridge on Node 2 connecting local pods. Decapsulated traffic arrives here.',
    shape: 'rectangle',
    color: '#22c55e',
    position: { x: 610, y: 120 },
    zone: 'node-2',
    ipAddress: '10.244.2.1',
  },
  {
    id: 'veth-b',
    name: 'veth pair',
    description: 'Virtual ethernet pair for Pod B. Connects bridge to pod network namespace.',
    shape: 'pipe',
    color: '#8b5cf6',
    position: { x: 710, y: 100 },
    zone: 'node-2',
  },
  {
    id: 'pod-b-netns',
    name: 'Net NS',
    description: 'Network namespace for Pod B. Receives the decapsulated packet on eth0.',
    shape: 'rectangle',
    color: '#6366f1',
    position: { x: 780, y: 165 },
    zone: 'pod-b-zone',
  },
  {
    id: 'pod-b',
    name: 'Pod B',
    description: 'Destination pod receiving the connection. Runs the service that Pod A wants to reach.',
    shape: 'hexagon',
    color: '#10b981',
    position: { x: 785, y: 80 },
    zone: 'pod-b-zone',
    ipAddress: '10.244.2.8',
  },
];

export const podToPodSteps: PodToPodStep[] = [
  {
    id: 'step1',
    from: 'pod-a',
    to: 'pod-a-netns',
    label: '1. App Sends Packet',
    description: 'Application in Pod A sends a TCP packet to Pod B\'s IP address (10.244.2.8).',
    duration: 1500,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'App calls connect(10.244.2.8:8080)',
      'Kernel creates TCP SYN packet',
      'Source: 10.244.1.5, Dest: 10.244.2.8',
      'Packet enters pod network namespace',
    ],
  },
  {
    id: 'step2',
    from: 'pod-a-netns',
    to: 'veth-a',
    label: '2. Route Lookup',
    description: 'Kernel performs route lookup. Default route points to veth interface (eth0 inside pod).',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'Route table: 10.244.0.0/16 via eth0',
      'Packet sent to eth0 (veth inside pod)',
      'veth pair connects to host namespace',
      'ARP resolves gateway MAC address',
    ],
  },
  {
    id: 'step3',
    from: 'veth-a',
    to: 'bridge-1',
    label: '3. Bridge Receives',
    description: 'Packet exits veth pair and arrives at the CNI bridge (cbr0/cni0) on the host.',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'veth peer on host attached to bridge',
      'Bridge receives frame on port',
      'Bridge performs MAC learning',
      'Checks if destination is local',
    ],
  },
  {
    id: 'step4',
    from: 'bridge-1',
    to: 'node-1-eth',
    label: '4. Not Local - Route',
    description: 'Destination pod is not on this node. Packet is routed to the node\'s physical interface.',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      '10.244.2.8 not in local ARP table',
      'Route: 10.244.2.0/24 via 192.168.1.11',
      'Packet forwarded to eth0',
      'CNI plugin manages these routes',
    ],
  },
  {
    id: 'step5',
    from: 'node-1-eth',
    to: 'overlay-network',
    label: '5. VXLAN Encapsulation',
    description: 'CNI plugin encapsulates the pod packet in a VXLAN header for overlay transport.',
    duration: 1500,
    packetType: 'encapsulated',
    packetLabel: 'VXLAN',
    details: [
      'Original packet becomes inner payload',
      'VXLAN header added (VNI: 4096)',
      'Outer IP: 192.168.1.10 → 192.168.1.11',
      'Outer UDP port: 4789 (VXLAN)',
    ],
  },
  {
    id: 'step6',
    from: 'overlay-network',
    to: 'cni-plugin',
    label: '6. CNI Routes Packet',
    description: 'CNI plugin (Calico/Flannel) determines the destination node based on pod CIDR.',
    duration: 1200,
    packetType: 'data',
    details: [
      'CNI maintains pod-to-node mapping',
      '10.244.2.0/24 → Node 2 (192.168.1.11)',
      'VTEP (VXLAN Tunnel Endpoint) on each node',
      'Encapsulated packet sent over network',
    ],
  },
  {
    id: 'step7',
    from: 'cni-plugin',
    to: 'node-2-eth',
    label: '7. Arrives at Node 2',
    description: 'Encapsulated packet arrives at Node 2\'s physical interface.',
    duration: 1200,
    packetType: 'encapsulated',
    packetLabel: 'VXLAN',
    details: [
      'Packet received on eth0',
      'Kernel identifies VXLAN (UDP 4789)',
      'VTEP processes the packet',
      'Ready for decapsulation',
    ],
  },
  {
    id: 'step8',
    from: 'node-2-eth',
    to: 'bridge-2',
    label: '8. VXLAN Decapsulation',
    description: 'VXLAN header is stripped, revealing the original pod-to-pod packet.',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'Outer headers removed',
      'Inner packet: 10.244.1.5 → 10.244.2.8',
      'Original TCP SYN revealed',
      'Forwarded to CNI bridge',
    ],
  },
  {
    id: 'step9',
    from: 'bridge-2',
    to: 'veth-b',
    label: '9. Bridge Forwards',
    description: 'Bridge looks up destination MAC and forwards to the correct veth port for Pod B.',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'Bridge MAC table lookup',
      'Destination: Pod B veth MAC',
      'Frame forwarded to veth port',
      'Enters Pod B network namespace',
    ],
  },
  {
    id: 'step10',
    from: 'veth-b',
    to: 'pod-b-netns',
    label: '10. Enter Pod Namespace',
    description: 'Packet crosses veth pair into Pod B\'s network namespace.',
    duration: 1000,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'veth delivers to pod namespace',
      'Appears on eth0 inside pod',
      'Kernel processes incoming packet',
      'TCP stack receives SYN',
    ],
  },
  {
    id: 'step11',
    from: 'pod-b-netns',
    to: 'pod-b',
    label: '11. App Receives',
    description: 'Application in Pod B receives the connection request on port 8080.',
    duration: 1200,
    packetType: 'tcp-syn',
    packetLabel: 'SYN',
    details: [
      'Socket listening on 0.0.0.0:8080',
      'Kernel delivers to socket',
      'TCP handshake: SYN received',
      'App accept() returns new connection',
    ],
  },
  {
    id: 'step12',
    from: 'pod-b',
    to: 'pod-a',
    label: '12. Response (Reverse)',
    description: 'Pod B sends SYN-ACK back. Response follows the same path in reverse.',
    duration: 1500,
    packetType: 'tcp-ack',
    packetLabel: 'SYN-ACK',
    details: [
      'TCP SYN-ACK sent to 10.244.1.5',
      'Same path in reverse direction',
      'VXLAN encap/decap on return',
      'Connection established!',
    ],
  },
];

export function getComponentById(id: string): PodToPodComponent | undefined {
  return podToPodComponents.find(c => c.id === id);
}

export const networkNamespaces = {
  podA: {
    name: 'pod-a-netns',
    interfaces: ['eth0: 10.244.1.5/24'],
    routes: [
      'default via 10.244.1.1 dev eth0',
      '10.244.1.0/24 dev eth0 scope link',
    ],
  },
  podB: {
    name: 'pod-b-netns',
    interfaces: ['eth0: 10.244.2.8/24'],
    routes: [
      'default via 10.244.2.1 dev eth0',
      '10.244.2.0/24 dev eth0 scope link',
    ],
  },
};

export const vxlanInfo = {
  vni: 4096,
  port: 4789,
  mtu: 1450,
  encapOverhead: '50 bytes',
};

export const cniInfo = {
  plugin: 'Calico/Flannel',
  podCIDR: '10.244.0.0/16',
  nodeCIDRs: [
    { node: 'Node 1', cidr: '10.244.1.0/24', ip: '192.168.1.10' },
    { node: 'Node 2', cidr: '10.244.2.0/24', ip: '192.168.1.11' },
  ],
};
