// K8s Components and Flow Data

import type { K8sComponent, Flow, ComponentId } from './types';

export const components: K8sComponent[] = [
  // External
  {
    id: 'kubectl',
    name: 'kubectl',
    description: 'Command-line tool for K8s API',
    shape: 'rectangle',
    color: '#64748b',
    position: { x: 50, y: 150 },
    node: 'external',
  },
  {
    id: 'ingress',
    name: 'Ingress',
    description: 'External traffic entry point',
    shape: 'pentagon',
    color: '#f59e0b',
    position: { x: 50, y: 300 },
    node: 'external',
  },

  // Master Node Components - positioned within left box (180-560px)
  {
    id: 'api-server',
    name: 'API Server',
    description: 'Central management hub, validates and processes API requests',
    shape: 'hexagon',
    color: '#326CE5',
    position: { x: 280, y: 180 },
    node: 'master',
  },
  {
    id: 'etcd',
    name: 'etcd',
    description: 'Distributed key-value store for cluster state',
    shape: 'circle',
    color: '#419eda',
    position: { x: 420, y: 80 },
    node: 'master',
  },
  {
    id: 'scheduler',
    name: 'Scheduler',
    description: 'Assigns pods to nodes based on resources',
    shape: 'triangle',
    color: '#22c55e',
    position: { x: 220, y: 60 },
    node: 'master',
  },
  {
    id: 'controller-manager',
    name: 'Controller Manager',
    description: 'Runs controller processes (ReplicaSet, Deployment, etc.)',
    shape: 'diamond',
    color: '#8b5cf6',
    position: { x: 450, y: 280 },
    node: 'master',
  },

  // Worker Node Components - positioned within right box (600-980px)
  {
    id: 'kubelet',
    name: 'Kubelet',
    description: 'Node agent that manages pod lifecycle',
    shape: 'octagon',
    color: '#ec4899',
    position: { x: 680, y: 80 },
    node: 'worker',
  },
  {
    id: 'container-runtime',
    name: 'Container Runtime',
    description: 'Runs containers (Docker, containerd)',
    shape: 'square',
    color: '#06b6d4',
    position: { x: 680, y: 230 },
    node: 'worker',
  },
  {
    id: 'kube-proxy',
    name: 'Kube Proxy',
    description: 'Network proxy for service routing',
    shape: 'diamond',
    color: '#f97316',
    position: { x: 850, y: 80 },
    node: 'worker',
  },
  {
    id: 'pod',
    name: 'Pod',
    description: 'Smallest deployable unit in K8s',
    shape: 'circle',
    color: '#10b981',
    position: { x: 850, y: 230 },
    node: 'worker',
  },
  {
    id: 'service',
    name: 'Service',
    description: 'Stable network endpoint for pods',
    shape: 'hexagon',
    color: '#6366f1',
    position: { x: 760, y: 350 },
    node: 'worker',
  },

  // Abstract components (for deployment flow) - within master node, spread out more
  {
    id: 'deployment',
    name: 'Deployment',
    description: 'Manages ReplicaSets and rolling updates',
    shape: 'rectangle',
    color: '#8b5cf6',
    position: { x: 200, y: 340 },
    node: 'master',
  },
  {
    id: 'replicaset',
    name: 'ReplicaSet',
    description: 'Ensures desired number of pod replicas',
    shape: 'rectangle',
    color: '#a855f7',
    position: { x: 360, y: 340 },
    node: 'master',
  },
];

export const flows: Flow[] = [
  {
    id: 'pod-creation',
    name: 'Pod Creation Flow',
    description: 'How a pod is created when you run kubectl create pod',
    steps: [
      {
        id: 'step1',
        from: 'kubectl',
        to: 'api-server',
        label: '1. kubectl create pod',
        description: 'User sends pod creation request via kubectl CLI',
        duration: 1500,
      },
      {
        id: 'step2',
        from: 'api-server',
        to: 'etcd',
        label: '2. Persist to etcd',
        description: 'API Server validates request and stores pod spec in etcd',
        duration: 1200,
      },
      {
        id: 'step3',
        from: 'api-server',
        to: 'scheduler',
        label: '3. Notify Scheduler',
        description: 'Scheduler watches for unscheduled pods',
        duration: 1000,
      },
      {
        id: 'step4',
        from: 'scheduler',
        to: 'api-server',
        label: '4. Bind to Node',
        description: 'Scheduler selects best node and updates pod binding',
        duration: 1200,
      },
      {
        id: 'step5',
        from: 'api-server',
        to: 'etcd',
        label: '5. Update binding',
        description: 'Pod-to-node binding is persisted in etcd',
        duration: 1000,
      },
      {
        id: 'step6',
        from: 'api-server',
        to: 'kubelet',
        label: '6. Notify Kubelet',
        description: 'Kubelet watches for pods assigned to its node',
        duration: 1200,
      },
      {
        id: 'step7',
        from: 'kubelet',
        to: 'container-runtime',
        label: '7. Create containers',
        description: 'Kubelet instructs container runtime to pull image and start containers',
        duration: 1500,
      },
      {
        id: 'step8',
        from: 'container-runtime',
        to: 'pod',
        label: '8. Pod Running',
        description: 'Containers are started and pod enters Running state',
        duration: 1000,
      },
    ],
  },
  {
    id: 'deployment',
    name: 'Deployment Flow',
    description: 'How a deployment creates and manages pods',
    steps: [
      {
        id: 'step1',
        from: 'kubectl',
        to: 'api-server',
        label: '1. kubectl apply deployment',
        description: 'User creates/updates a Deployment resource',
        duration: 1500,
      },
      {
        id: 'step2',
        from: 'api-server',
        to: 'etcd',
        label: '2. Store Deployment',
        description: 'Deployment spec is stored in etcd',
        duration: 1200,
      },
      {
        id: 'step3',
        from: 'api-server',
        to: 'controller-manager',
        label: '3. Deployment Controller watches',
        description: 'Deployment controller detects new deployment',
        duration: 1000,
      },
      {
        id: 'step4',
        from: 'controller-manager',
        to: 'replicaset',
        label: '4. Create ReplicaSet',
        description: 'Deployment controller creates a ReplicaSet via API Server',
        duration: 1200,
      },
      {
        id: 'step5',
        from: 'api-server',
        to: 'etcd',
        label: '5. Store ReplicaSet',
        description: 'ReplicaSet spec is stored in etcd',
        duration: 1000,
      },
      {
        id: 'step6',
        from: 'replicaset',
        to: 'api-server',
        label: '6. ReplicaSet creates Pods',
        description: 'ReplicaSet controller creates pod specs via API Server',
        duration: 1200,
      },
      {
        id: 'step7',
        from: 'scheduler',
        to: 'api-server',
        label: '7. Schedule Pods',
        description: 'Scheduler assigns pods to nodes',
        duration: 1200,
      },
      {
        id: 'step8',
        from: 'api-server',
        to: 'kubelet',
        label: '8. Kubelet creates Pods',
        description: 'Kubelet starts containers on assigned node',
        duration: 1500,
      },
      {
        id: 'step9',
        from: 'kubelet',
        to: 'pod',
        label: '9. Pod Running',
        description: 'Containers are started and pod enters Running state',
        duration: 1000,
      },
    ],
  },
  {
    id: 'service-request',
    name: 'Service Request Flow',
    description: 'How external traffic reaches a pod through Service',
    steps: [
      {
        id: 'step1',
        from: 'ingress',
        to: 'kube-proxy',
        label: '1. External Request',
        description: 'Traffic enters cluster through Ingress/LoadBalancer',
        duration: 1200,
      },
      {
        id: 'step2',
        from: 'kube-proxy',
        to: 'service',
        label: '2. Route to Service',
        description: 'Kube-proxy routes traffic to Service ClusterIP',
        duration: 1000,
      },
      {
        id: 'step3',
        from: 'service',
        to: 'pod',
        label: '3. Load Balance to Pod',
        description: 'Service load balances to healthy pod endpoints',
        duration: 1200,
      },
      {
        id: 'step4',
        from: 'pod',
        to: 'service',
        label: '4. Response',
        description: 'Pod processes request and sends response',
        duration: 1000,
      },
      {
        id: 'step5',
        from: 'service',
        to: 'kube-proxy',
        label: '5. Return path',
        description: 'Response travels back through service',
        duration: 1000,
      },
      {
        id: 'step6',
        from: 'kube-proxy',
        to: 'ingress',
        label: '6. Exit cluster',
        description: 'Response exits cluster to client',
        duration: 1200,
      },
    ],
  },
];

export function getComponentById(id: ComponentId): K8sComponent | undefined {
  return components.find(c => c.id === id);
}

export function getFlowById(id: string): Flow | undefined {
  return flows.find(f => f.id === id);
}
