// Persistent Volume / PVC Flow - Components and Flow Data

import type { PvFlowComponent, PvFlowStep } from './types';

export const pvFlowComponents: PvFlowComponent[] = [
  {
    id: 'user',
    name: 'User',
    description: 'Admin or developer applying PV, PVC, and pod manifests',
    shape: 'circle',
    color: '#94a3b8',
    position: { x: 40, y: 200 },
    zone: 'client',
  },
  {
    id: 'kubectl',
    name: 'kubectl',
    description: 'CLI that sends PV, PVC, and pod resources to the API Server',
    shape: 'rectangle',
    color: '#64748b',
    position: { x: 130, y: 200 },
    zone: 'client',
  },
  {
    id: 'api-server',
    name: 'API Server',
    description: 'Validates and persists PV, PVC, and pod objects',
    shape: 'hexagon',
    color: '#326CE5',
    position: { x: 320, y: 200 },
    zone: 'api-layer',
  },
  {
    id: 'etcd',
    name: 'etcd',
    description: 'Stores PV, PVC, and pod specs as cluster state',
    shape: 'circle',
    color: '#419eda',
    position: { x: 520, y: 200 },
    zone: 'api-layer',
  },
  {
    id: 'pv-controller',
    name: 'PV Controller',
    description: 'Binds matching PersistentVolumes to PersistentVolumeClaims',
    shape: 'diamond',
    color: '#8b5cf6',
    position: { x: 400, y: 340 },
    zone: 'control-plane',
  },
  {
    id: 'storage-backend',
    name: 'Storage Backend',
    description: 'Physical storage (NFS, hostPath, EBS, etc.) backing the PV',
    shape: 'pentagon',
    color: '#f59e0b',
    position: { x: 40, y: 400 },
    zone: 'external',
  },
  {
    id: 'pv',
    name: 'PersistentVolume',
    description: 'Cluster-scoped storage resource (Available → Bound)',
    shape: 'square',
    color: '#14b8a6',
    position: { x: 280, y: 420 },
    zone: 'storage',
  },
  {
    id: 'pvc',
    name: 'PersistentVolumeClaim',
    description: 'Namespace-scoped request for storage (Pending → Bound)',
    shape: 'square',
    color: '#6366f1',
    position: { x: 440, y: 420 },
    zone: 'storage',
  },
  {
    id: 'pod-spec',
    name: 'Pod + PVC',
    description: 'Pod manifest referencing the PVC via volumes.claimName',
    shape: 'rectangle',
    color: '#a855f7',
    position: { x: 600, y: 80 },
    zone: 'worker-node',
  },
  {
    id: 'kubelet',
    name: 'Kubelet',
    description: 'Node agent that mounts volumes for pods on this node',
    shape: 'octagon',
    color: '#ec4899',
    position: { x: 700, y: 200 },
    zone: 'worker-node',
  },
  {
    id: 'volume-manager',
    name: 'Volume Manager',
    description: 'Kubelet subsystem that attaches and mounts volumes',
    shape: 'diamond',
    color: '#f97316',
    position: { x: 850, y: 200 },
    zone: 'worker-node',
  },
  {
    id: 'container',
    name: 'Container',
    description: 'Running container with volume mounted at mountPath',
    shape: 'circle',
    color: '#3b82f6',
    position: { x: 920, y: 360 },
    zone: 'worker-node',
  },
];

export const pvFlowSteps: PvFlowStep[] = [
  {
    id: 'step1',
    from: 'user',
    to: 'kubectl',
    label: '1. Apply manifests',
    description: 'User runs kubectl apply for PV, PVC, and pod YAML files',
    duration: 1200,
    details: [
      'pv.yaml defines capacity, accessModes, storageClassName',
      'pvc.yaml requests storage size in a namespace',
      'pod.yaml references the PVC in volumes[].persistentVolumeClaim',
    ],
  },
  {
    id: 'step2',
    from: 'kubectl',
    to: 'api-server',
    label: '2. Create PV & PVC',
    description: 'kubectl sends PV and PVC resources to the API Server',
    duration: 1000,
    details: [
      'POST /api/v1/persistentvolumes',
      'POST /api/v1/namespaces/{ns}/persistentvolumeclaims',
      'PV phase: Available; PVC phase: Pending',
    ],
  },
  {
    id: 'step3',
    from: 'api-server',
    to: 'etcd',
    label: '3. Persist to etcd',
    description: 'API Server stores PV and PVC objects in etcd',
    duration: 1200,
    details: [
      'PV stored at cluster scope',
      'PVC stored under namespace',
      'Both visible to controllers via watch',
    ],
  },
  {
    id: 'step4',
    from: 'storage-backend',
    to: 'pv',
    label: '4. Provision storage',
    description: 'Admin-provisioned PV is backed by real storage',
    duration: 1500,
    details: [
      'hostPath, NFS, iSCSI, or cloud disk path',
      'PV spec describes the backend volume',
      'PV remains Available until bound',
    ],
  },
  {
    id: 'step5',
    from: 'api-server',
    to: 'pv-controller',
    label: '5. Controller watches PVC',
    description: 'PersistentVolume controller detects unbound PVC',
    duration: 1000,
    details: [
      'Controller runs in kube-controller-manager',
      'Watches PVCs in Pending phase',
      'Searches for matching Available PV',
    ],
  },
  {
    id: 'step6',
    from: 'pv-controller',
    to: 'pv',
    label: '6. Match PV to PVC',
    description: 'Controller finds PV matching size, access modes, and storage class',
    duration: 1200,
    details: [
      'Capacity must meet or exceed PVC request',
      'accessModes must be compatible',
      'storageClassName must match (if set)',
    ],
  },
  {
    id: 'step7',
    from: 'pv',
    to: 'pvc',
    label: '7. Bind PV ↔ PVC',
    description: 'PV and PVC are bound; both enter Bound phase',
    duration: 1500,
    details: [
      'PV claimRef set to the PVC',
      'PVC volumeName set to PV name',
      'PVC phase: Pending → Bound',
    ],
  },
  {
    id: 'step8',
    from: 'pvc',
    to: 'etcd',
    label: '8. Update bound state',
    description: 'Bound relationship persisted in etcd',
    duration: 800,
    details: [
      'Binding is durable cluster state',
      'Pod can now reference this PVC',
    ],
  },
  {
    id: 'step9',
    from: 'user',
    to: 'pod-spec',
    label: '9. Pod references PVC',
    description: 'Pod spec includes volumeMount and persistentVolumeClaim',
    duration: 1000,
    details: [
      'volumes[].persistentVolumeClaim.claimName: my-pvc',
      'volumeMounts[].mountPath: /data',
      'Scheduler may consider volume topology',
    ],
  },
  {
    id: 'step10',
    from: 'pod-spec',
    to: 'api-server',
    label: '10. Create pod',
    description: 'Pod creation request sent through API Server',
    duration: 1000,
    details: [
      'Pod scheduled only after PVC is Bound',
      'Kubelet will mount volume before container starts',
    ],
  },
  {
    id: 'step11',
    from: 'api-server',
    to: 'kubelet',
    label: '11. Kubelet assigned pod',
    description: 'Kubelet on the node receives the pod with volume requirements',
    duration: 1200,
    details: [
      'Kubelet sync loop processes pod',
      'Identifies PVCs referenced by pod volumes',
    ],
  },
  {
    id: 'step12',
    from: 'kubelet',
    to: 'volume-manager',
    label: '12. Mount volume',
    description: 'Volume manager attaches and mounts the PV for this pod',
    duration: 1500,
    details: [
      'Map PVC to bound PV on the node',
      'Attach volume plugin (NFS, hostPath, etc.)',
      'Prepare mount point on the node',
    ],
  },
  {
    id: 'step13',
    from: 'volume-manager',
    to: 'pv',
    label: '13. Use bound PV',
    description: 'Volume manager uses the PersistentVolume backing the claim',
    duration: 1200,
    details: [
      'Global mount path on node',
      'SubPath bind if configured',
      'Volume ready for pod consumption',
    ],
  },
  {
    id: 'step14',
    from: 'volume-manager',
    to: 'container',
    label: '14. Mount in container',
    description: 'Volume bind-mounted into container at mountPath',
    duration: 1200,
    details: [
      'Container sees persistent data at /data (example)',
      'Data survives pod restarts while PVC remains bound',
      'Application can read/write persistent storage',
    ],
  },
];

export function getPvComponentById(id: string): PvFlowComponent | undefined {
  return pvFlowComponents.find((c) => c.id === id);
}
